# Generated by Django 2.0.1 on 2018-01-05 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=200, unique=True)),
                ('boss_user_id', models.IntegerField()),
                ('command_args', models.TextField()),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('post_errors', models.IntegerField(default=0)),
                ('load_errors', models.IntegerField(default=0)),
                ('z_start', models.IntegerField()),
                ('z_end', models.IntegerField()),
                ('z_current', models.IntegerField(null=True)),
            ],
        ),
    ]
