# Generated by Django 2.0.1 on 2018-01-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingestjob',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingestjob',
            name='unique_id',
            field=models.CharField(help_text='md5 hash of ingest_job', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='ingestjob',
            name='z_current',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
